In [5]:
import pandas as pd
import numpy as np
import pickle
import warnings
warnings.filterwarnings('ignore')
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# from xgboost import XGBRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,ConfusionMatrixDisplay,precision_score,recall_score,f1_score,classification_report,roc_curve,plot_roc_curve,auc,precision_recall_curve,plot_precision_recall_curve,average_precision_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
import os

In [26]:
pd.set_option("display.max_columns", None)

In [27]:
df_pisos = pd.read_csv('pisos_nuevo.csv')
df_pisos

,sq_mt_built,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,floor,buy_price,is_renewal_needed,has_lift,is_exterior,energy_certificate,has_parking,neighborhood,district,fecha_venta,mean_price_district,std_deviation_price_district,1,3,4,5
0,64.0,2,1,1,0.0,3,85000,0,0,1,4,0,135,21,2018-12-16 10:43:16,165506.178439,67521.938284,1,0,0,0
1,70.0,3,1,1,0.0,4,129900,1,1,1,0,0,132,21,1994-07-09 21:18:56,165506.178439,67521.938284,1,0,0,0
2,94.0,2,2,1,0.0,1,144247,0,1,1,0,0,134,21,1999-08-23 00:13:51,165506.178439,67521.938284,1,0,0,0
3,64.0,2,1,1,0.0,-1,109900,0,1,1,0,0,134,21,2012-10-20 09:20:20,165506.178439,67521.938284,1,0,0,0
4,108.0,2,2,1,0.0,4,260000,0,1,1,0,1,133,21,2011-03-19 07:39:04,165506.178439,67521.938284,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19796,99.0,2,2,1,0.0,1,349000,0,1,1,0,1,9,2,2002-07-22 12:03:07,400558.333333,177988.858754,1,0,0,0
19797,78.0,2,2,1,0.0,4,350000,0,1,1,0,1,10,2,1996-06-04 15:46:37,400558.333333,177988.858754,0,0,0,1
19798,96.0,2,2,1,0.0,3,425000,0,1,1,0,1,9,2,2011-03-12 13:05:51,400558.333333,177988.858754,1,0,0,0
19799,175.0,4,2,1,0.0,-1,680000,0,0,1,3,1,9,2,1992-09-06 09:16:35,400558.333333,177988.858754,1,0,0,0
19800,72.0,2,2,1,0.0,2,424000,0,1,1,7,1,3,1,2007-03-21 09:05:58,374305.042914,164570.883259,1,0,0,0

In [28]:

X  = df_pisos[['sq_mt_built','n_rooms','n_bathrooms','is_renewal_needed','has_parking']]
y = df_pisos['buy_price']
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=42)

In [29]:
models = []
# models.append(['XGBRegressor',XGBRegressor(random_state=0)])
models.append(['SVR',SVR()])
models.append(['KNeigborsRegressor',KNeighborsRegressor()])
models.append(['DecisionTreeRegressor',DecisionTreeRegressor(random_state=0)])
models.append(['RandomForestRegressor',RandomForestRegressor(random_state=0)])
models.append(['AdaBoostRegressor',AdaBoostRegressor()])
models.append(['GradientBoostinRegressor',GradientBoostingRegressor(random_state=0)])

In [30]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
lst_1 = []

for m in range(len(models)):
    lst_2 = []
    model = models[m][1]
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)

# metrics
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test,y_pred))

    print(models[m][0],':')
    # print(cm)
    print('MAE: ', mae)
    print('RMSE: ', rmse)
    print('--------------------------------')
    lst_2.append(models[m][0])
    lst_2.append(mae)
    lst_2.append(rmse)
    lst_1.append(lst_2)

XGBRegressor :
MAE:  162881.6999247404
RMSE:  312134.10067906335
--------------------------------
SVR :
MAE:  343247.208456263
RMSE:  632627.5182678599
--------------------------------
KNeigborsRegressor :
MAE:  170529.8083580582
RMSE:  304598.6083352007
--------------------------------
DecisionTreeRegressor :
MAE:  192814.9061002224
RMSE:  382946.0005635473
--------------------------------
RandomForestRegressor :
MAE:  165240.92909446562
RMSE:  296002.7985322763
--------------------------------
AdaBoostRegressor :
MAE:  192923.52882933154
RMSE:  312013.7511109525
--------------------------------
GradientBoostinRegressor :
MAE:  157627.0056040588
RMSE:  284375.36302597047
--------------------------------

In [31]:
df2 = pd.DataFrame(lst_1,columns=['Model','MAE','RMSE'])
df2.sort_values(by='RMSE',inplace=True,ascending=True)
df2

                      Model            MAE           RMSE
6  GradientBoostinRegressor  157627.005604  284375.363026
4     RandomForestRegressor  165240.929094  296002.798532
2        KNeigborsRegressor  170529.808358  304598.608335
5         AdaBoostRegressor  192923.528829  312013.751111
0              XGBRegressor  162881.699925  312134.100679
3     DecisionTreeRegressor  192814.906100  382946.000564
1                       SVR  343247.208456  632627.518268

In [32]:
parameters = {
            "n_estimators": [10, 100, 200, 500, 1000], 
            "max_depth": [5,10,15,20],
            "max_features": [1,2, 3, 4, 7,9,12,14, 20, 25, 29] 
            }

model = RandomForestRegressor()

gs = GridSearchCV(estimator = model,
                  param_grid = parameters,
                  cv=10, 
                  scoring='neg_mean_absolute_error', 
                  verbose=1, 
                  n_jobs=-1)

gs.fit(X_train, y_train)

Fitting 10 folds for each of 220 candidates, totalling 2200 fits

GridSearchCV(cv=10, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15, 20],
                         'max_features': [1, 2, 3, 4, 7, 9, 12, 14, 20, 25, 29],
                         'n_estimators': [10, 100, 200, 500, 1000]},
             scoring='neg_mean_absolute_error', verbose=1)

In [33]:
print("best estimator: ",gs.best_estimator_)
print("best params: ",gs.best_params_)
print("best score: ",gs.best_score_)

best estimator:  RandomForestRegressor(max_depth=10, max_features=2, n_estimators=1000)
best params:  {'max_depth': 10, 'max_features': 2, 'n_estimators': 1000}
best score:  -160869.98094095438

In [38]:
# Error de test del modelo final
# ==============================================================================
modelo_final = gs.best_estimator_  ## aquí tengo almacenado el modelo con los mejores parametros definidos
predicciones = gs.predict(X_test)

print('MAE:', round(mean_absolute_error(y_test, predicciones),4))
print('MSE:', round(mean_squared_error(y_test, predicciones),4))
print('RMSE:', round(np.sqrt(mean_squared_error(y_test, predicciones)),4))

MAE: 154888.3777
MSE: 78875187135.5979
RMSE: 280847.2666

In [ ]:
modelo = RandomForestRegressor(max_depth=10, max_features=2, n_estimators=1000)
modelo.fit(X, y)

In [39]:
## guardo el modelo en esta misma ruta de donde tengo el notebook
filename = 'pisos_Rand_For.model'   ### es un archivo tipo pickel que me está guardando mi modelo (se crea cuando ejecuto esta celda)

with open(filename, 'wb') as archivo_salida:
    pickle.dump(modelo, archivo_salida)

In [40]:
## hago una prueba de cargar ese modelo guardado

with open('pisos_Rand_For.model', "rb") as archivo_entrada:
    importado = pickle.load(archivo_entrada)

RandomForestRegressor(max_depth=10, max_features=2, n_estimators=1000)

In [ ]:
X=[[100,3,2,0,1]]

In [ ]:
pred = importado.predict(X)
pred